---
name: isotovideo
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            This is your comment. Can I go now?
